services:
  api:
    build:
      context: .
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    image: medrush-app:latest
    container_name: medrush-api
    restart: always
    env_file: .env
    volumes:
      - ./storage/app:/var/www/laravel-app/storage/app
    networks:
      - medrush-network

  worker:
    image: medrush-app:latest
    container_name: medrush-worker
    restart: always
    env_file: .env
    command: php artisan queue:work --tries=3 --timeout=600
    volumes:
      - ./storage/app:/var/www/laravel-app/storage/app
    depends_on:
      - api
    networks:
      - medrush-network

  reverb:
    image: medrush-app:latest
    container_name: medrush-reverb
    restart: always
    env_file: .env
    command: php artisan reverb:start --host=0.0.0.0 --port=9000
    ports:
      - "9000:9000"
    depends_on:
      - api
    networks:
      - medrush-network

  nginx:
    image: nginx:alpine
    container_name: medrush-nginx
    ports:
      - "4000:80"
    volumes:
      - .:/var/www/laravel-app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - medrush-network

networks:
  medrush-network:
    driver: bridge
