services:
  api:
    build:
      context: .
    restart: always
    volumes:
      - storage-data:/var/www/laravel-app/storage/app

  worker:
    build:
      context: .
    restart: always
    command: php artisan queue:work --tries=3 --timeout=600
    depends_on:
      - api
    volumes:
      - storage-data:/var/www/laravel-app/storage/app

  reverb:
    build:
      context: .
    restart: always
    command: php artisan reverb:start --host=0.0.0.0 --port=9000
    depends_on:
      - api

volumes:
  storage-data:
